### PR TITLE
PR / Issue automation - Better setup script

### PR DESCRIPTION
**Pull request by Eventyret**
**Description:**
- Changed ISSUE_TEMPLATE for GitHub (adding comments instead of just text, saving people from removing test)
- Added ISSUE_TEMPLTE for Pull Requests (Standard info so feel free to tweak or make comments to this)
- Removed files that were not needed
- `setup.sh` and `setup.bat` will not install the python extensions for Vscode (Requires reload of VSCode)
- `setup.sh` will now check if Pipfile is present if it is it will use this (saves time) if not falls back to requirements.
- `setup.sh` and `setup.bat` will now install `pylint pylint-django pep8 autopep8` this should help with Vscode and lining issues for best Pep8 practices
- `setup.sh` and `setup.bat` will now create a `vscode/settings.json` this to hold linting info and also should auto-detect if a virtual environment is selected
- Pipenv is included and should not be excluded (this will be like a requirements.txt) and will help with pipenv for those using VSCode (Heroku also supports it)

**Related Issue:**

N/A

**Configuration instructions:**

N/A

**Screenshots:**
UI

**Additional Information:**
Would love some help with the `bat` and convert it I'm on mac so unable to test setup.bat feel free to make a PR towards this or use what has been generated and modify accordingly.

### CODE REVIEW

**Review by stefdworschak — APPROVED** [review]
LGTM

**Comment by Eventyret** [comment]
@JimLynx  if you want to for the bat file do let me know and we can have a session and fun.

**Comment by JimLynx** [comment]
That would be super @Eventyret

**Comment by Eventyret** [comment]
@TravelTimN Would this go towrds the accepted tag for Hacktober please ?

**Pull request merged**
